//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTSMembers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2013
    {
        public int ID { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Street_Address { get; set; }
        public string City { get; set; }
        public string Phone_Number_1 { get; set; }
        public string Phone_Number_2 { get; set; }
        public string EmailAddress_1 { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public Nullable<bool> OkToAddToAddressBook { get; set; }
        public string Company { get; set; }
        public string Job_Title { get; set; }
        public string Work_Number { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
