// <auto-generated />
namespace OTSMembers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _32134 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_32134));
        
        string IMigrationMetadata.Id
        {
            get { return "201504010548412_32134"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
