// <auto-generated />
namespace OTSMembers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _201503160725_AddStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201503160725_AddStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201503272226002__201503160725_AddStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
